# -*- coding: utf-8 -*-
"""locationCrime

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zaZ96ZbKIPU2qe_pb5buZNvj0cy5eDzC
"""

from google.colab import drive
drive.mount('/content/drive')

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df_crime=pd.read_csv('/content/drive/MyDrive/경찰청_범죄 발생 지역별 통계_20221231.csv',encoding='cp949')

#print(df_crime.loc[:,'범죄중분류'])

df_crime.shape

row=len(df_crime)
col=len(df_crime.columns)

search=input("범죄중분류명 입력: ")
location=input("지역명 입력: ")
# if df_crime.loc[2,'범죄중분류']==search:
#   print('same')

for i in range(row):
  if (df_crime.loc[i,'범죄중분류'])==search:
      showData=df_crime.loc[i,location]
      print("\n",location," ",search,showData,"건\n")
      print(df_crime.loc[[i]])
      # print(df_crime.columns)
      plt.rc('font",family')
      # plt.bar(df_crime.columns,df_crime.loc[i])
      break

